### ISSUE TITLE
Option to change keybind

### ISSUE THREAD

**Issue by ghost** [zMidair/Fullscreen-Keybind#2]
So the f11 conflicts with [Devtools](https://github.com/geode-sdk/DevTools). Can you make it that we can change the keybinds for fullscreen?

**Comment by zMidair** [comment]
Hello, this is already possible in the Custom Keybinds menu. Go to Settings > Options and in the top right of the window there shiuld be a button with the “Keys” (or smth like that) text on it. If you have trouble finding it let me know.

**Comment by ghost** [comment]
Oh yea i forgor about custom keybinds mod, mb
